config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  resources :tweets do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :content, length: {in:1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  def index
    @tweets = Tweet.all
  end
  def new
    @tweet = Tweet.new
  end
  def create
    @tweet = Tweet.new(tweet_params)
    if params[:back]
      render :new
    else
      if @tweet.save
        redirect_to new_tweet_path, notice: "ツイートを投稿しました！"
      else
        render :new
      end
    end
  end
  def show
  end
  def edit
  end
  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "ツイートを編集しました！"
    else
      render :edit
    end
  end
  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice:"ブログを削除しました！"
  end
  def confirm
    @tweet = Tweet.new(tweet_params)
    render :new if @tweet.invalid?
  end
  private
  def tweet_params
    params.require(:tweet).permit(:content)
  end
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterclone</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header class="header">twitterclone</header>
  <div align="center">
    <%= yield %>
  </div>
  <footer>
    <p>運営会社twitterclone株式会社</p>
    <p>© 2020-2021 Copyright twitterclone Corp.</p>
  </footer>
</body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: true ,url: choose_new_or_edit ) do |form| %>
<% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <div class="tweet_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to 'ツイート一覧画面に戻る', tweets_path %>

app/views/tweets/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @tweet, url: tweets_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <p>本文:<%= @tweet.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/tweets/edit.html.erb
<h2>ツイートを編集する</h2>
 <%= render 'form' %>

app/views/tweets/index.html.erb
<h3>ホーム</h3>
<table>
  <tr>
    <th>内容</th>
  </tr>
<% @tweets.each do |tweet| %>
  <tr>
    <td><%= tweet.content %></td>
    <td><%= link_to '詳細を確認する', tweet_path(tweet.id) %></td>
    <td><%= link_to "ブログを編集する", edit_tweet_path(tweet.id), data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to 'ブログを削除する', tweet_path(tweet.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>
<br>
<%= link_to '新しくツイートを投稿する', new_tweet_path %>

app/views/tweets/new.html.erb
<h2>ツイートを作成する</h2>
 <%= render 'form' %>

app/views/tweets/show.html.erb
<h1>ツイート詳細画面</h1>
<p>内容: <%= @tweet.content %></p>
<br>
<%= link_to 'ツイート一覧画面に戻る', tweets_path %>